### ISSUE TITLE
Request: Windows executeable

### ISSUE THREAD

**Issue by inxomnyaa** [jocopa3/PEWS-API#1]
Could you provide a pre-compiled version for windows? I do not understand how to build it and where to put the dependecies. Thanks! (does it even work in 1.0.4?)

**Comment by ioncorimenia** [comment]
Here you go: [PEWS.zip](https://github.com/jocopa3/PEWS-API/files/885782/PEWS.zip) I compiled it straight from pull request #2 and I downloaded the libs from their respective GitHub pages. Here's a [VirusTotal scan](https://www.virustotal.com/en/file/676a1e96be41343e19ba286fbc74d4392677456f4a00541ea20d56ddc06aa459/analysis/1490966945/) if you're still unsure. It runs `mcpews.listeners.ServerGUI` as it's main class.

**Comment by inxomnyaa** [comment]
Thanks alot! @jtvjan
